apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-java
  namespace: apps

spec:
  serviceName: backend-java-headless
  replicas: 1

  selector:
    matchLabels:
      app: backend-java

  template:
    metadata:
      labels:
        app: backend-java

    spec:
      containers:
        - name: backend-java
          image: nginx   

          ports:
            - containerPort: 80

          imagePullPolicy: IfNotPresent
